### ISSUE TITLE
last_epoch.h5 weights: ValueError: No such layer: activation_39

### ISSUE THREAD

**Issue by karolmajek** [srihari-humbarwadi/DeepLabV3_Plus-Tensorflow2.0#1]
Hi,

I'm trying to run inference in notebook.
Just downloaded `last_epoch.h5` and changed the filename here:
```
model = DeepLabV3Plus(h, w, 34)
model.load_weights('last_epoch.h5')  # was 'top_weights.h5'
```
I get this error:
```
*** Building DeepLabv3Plus Network ***
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-cc43d2a9a8cc> in <module>
----> 1 model = DeepLabV3Plus(h, w, 34)
      2 model.load_weights('last_epoch.h5')

~/projects/DeepLabV3_Plus-Tensorflow2.0/deeplab.py in DeepLabV3Plus(img_height, img_width, nclasses)
     67         img_height, img_width, 3), weights='imagenet', include_top=False)
     68 
---> 69     image_features = base_model.get_layer('activation_39').output
     70     x_a = ASPP(image_features)
     71     x_a = Upsample(tensor=x_a, size=[img_height // 4, img_width // 4])

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py in get_layer(self, name, index)
    520       if layer.name == name:
    521         return layer
--> 522     raise ValueError('No such layer: ' + name)
    523 
    524   @property

ValueError: No such layer: activation_39
```

**Comment by srihari-humbarwadi** [comment]
Ah yea, because I am fetching the layer by name, if the model is defined twice ( if the same cell in jupyter is executed twice), it leads to this situation because the new graph will have changed names. I will push a commit to fix this. In the meanwhile a hot fix should be restarting your kernel and then proceeding as usual!

**Comment by karolmajek** [comment]
Works, and results are good, thank you!

I modified pipeline to output original resolution `img_color = cv2.resize(img_color,(originalimage.shape[1],originalimage.shape[0]))` and renamed the firs parameter to `originalimage`

Bad news is `  0%|          | 45/45913 [02:58<51:58:45,  4.08s/it]`

**Comment by srihari-humbarwadi** [comment]
what are you running on? it took me 5~6 hours on 1080ti and i7 7820x, I have the video ready, I will upload and share it soon!

**Comment by karolmajek** [comment]
Laptop
GTX980M
i7 6700HQ 2.6GHz x 8

**Comment by xuexingyu24** [comment]
@karolmajek @srihari-humbarwadi   hi both,  wonder if there is a solution to avoid "ValueError: No such layer: activation_39" other than restarting the kernal ?

**Comment by srihari-humbarwadi** [comment]
Yes, you could fetch the layer by index instead of name. I might push this in a couple of days

**Comment by thuraaungjune** [comment]
No such layer: activation_39 is not ok with me srihari.
May i get more information ? Thanks
