### ISSUE TITLE
Syntax error in train.py->deeplab.py

### ISSUE THREAD

**Issue by mrengineer** [srihari-humbarwadi/DeepLabV3_Plus-Tensorflow2.0#10]
Hi, I am trying to re-train cityscapes.
In docker container with Python3 and TF2.0 I start train.py

But I see

> Traceback (most recent call last):
  File "train.py", line 4, in <module>
    from deeplab import DeepLabV3Plus
  File "/workspace/DeepLabV3_Plus-Tensorflow2.0/deeplab.py", line 29
    y_pool = BatchNormalization(name=f'bn_1')(y_pool)
                                           ^
SyntaxError: invalid syntax
>
Please, help to fix it.

**Comment by mrengineer** [comment]
It was because of Python & TF versions. Use latest

**Comment by srihari-humbarwadi** [comment]
Should work on python 3.6 and above
