### ISSUE TITLE
OSError:unable to open 'top_weights.h5' file

### ISSUE THREAD

**Issue by Alokksinha00** [srihari-humbarwadi/DeepLabV3_Plus-Tensorflow2.0#17]
Hi,
Thanks for the code. i tried to run the code and i see below OSE error: unable to open file. name: 'top_weights.h5'.
could you please help me to diagnose this? is it a problem with the file path?
![error](https://user-images.githubusercontent.com/51362254/68055426-9a384e80-fd16-11e9-8c9f-d67c4d3e55cc.JPG)

**Comment by srihari-humbarwadi** [comment]
You need to download the weights and then run the inference code

**Comment by Alokksinha00** [comment]
Thanks for the reply!
Did you mean the trained weights? ->https://drive.google.com/file/d/1wRXyIGUVRws3BJHX-UrNDSZGDzUzgVMx/view

**Comment by srihari-humbarwadi** [comment]
Yea, rename the file accordingly!
