### ISSUE TITLE
**/!\ DID YOU JUST GET SCAMMED /!\**

### ISSUE THREAD

**Issue by Tirbo06** [srihari-humbarwadi/DeepLabV3_Plus-Tensorflow2.0#26]
I clicked on this link on the top of your READ.ME : 
"HitCount" 

And an alert showed up to tell me that my general informations were stolen **!**
**What is this link for ????**

http://hits.dwyl.io/srihari-humbarwadi/https://githubcom/srihari-humbarwadi/DeepLabV3_Plus-Tensorflow20

**Comment by Tirbo06** [comment]
Did hits.dwyl.io got hacked !?

**Comment by srihari-humbarwadi** [comment]
Thank you for reporting this, I have removed the hit-count tag from the readme https://github.com/srihari-humbarwadi/DeepLabV3_Plus-Tensorflow2.0/commit/f06df320aebe4aeeeccfa789340b14c0df163b09.
Looks like hits dwyl io is got compromised!
